import { Selector } from 'testcafe';

fixture `MUCH overview`
    .page `http://mus.ph00a1.cz.infra/ui/`
    .httpAuth({
        username: 'much_tester',
        password: 'much_tester'
    })
    .beforeEach(async t => {
        await t
            .click('#IDToken1')
            .typeText('#IDToken1', 'much_tester')
            .click('#IDToken2')
            .typeText('#IDToken2', 'much_tester')
            .click('#kc-login');
    });

test('Geolocation tracking GUI', async t => {
    await t
        .click(Selector('header').nth(1).find('.MuiSvgIcon-root'))
        .expect(Selector('#GEO_TRACKING li').withText('Geolocation tracking').innerText).eql("Geolocation tracking")
        .click(Selector('#GEO_TRACKING li').withText('Geolocation tracking'))
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').exists).ok()
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').visible).ok()
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(1).exists).ok()
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(1).visible).ok()
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(2).exists).ok()
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(2).visible).ok()
        .expect(Selector('#geolocationFilterSelector span').withText('Team\'s position').innerText).eql("Team's position")
        .expect(Selector('.MuiIconButton-label').nth(5).find('.jss356').checked).ok()
        .expect(Selector('#geolocationTracking label').withText('LOCATION').innerText).contains("LOCATION")
        .expect(Selector('#locationButton').innerText).contains("Select location")
        .expect(Selector('#locationButton').visible).ok()
        .click('#locationButton')
        .expect(Selector('#location-dialog-title h2').withText('Select location').innerText).eql("Select location")
        .expect(Selector('#Region div').withText('​').nth(2).visible).ok()
        .click(Selector('#Region div').withText('​').nth(2))
        .expect(Selector('#menu- li').withText('Choose location').innerText).eql("Choose location")
        .click(Selector('#menu- em').withText('Choose location'))
        .expect(Selector('#acceptLocation').visible).ok()
        .click('#acceptLocation')
        .expect(Selector('#geolocationTracking label').withText('TEAM LEADER').innerText).eql("TEAM LEADER")
        .expect(Selector('#geolocationTracking div').withText('​').nth(9).visible).ok()
        .click(Selector('#geolocationTracking div').withText('​').nth(9))
        .expect(Selector('#menu- li').withText('Select team leader').innerText).contains("Select team leader")
        .click(Selector('#menu- li').withText('much_tester'))
        .expect(Selector('#geolocationTracking label').withText('LAST RESULT POSITION LIMIT').innerText).eql("LAST RESULT POSITION LIMIT")
        .expect(Selector('#geolocationTracking .jss356.MuiSwitch-input').visible).ok()
        .expect(Selector('#geolocationTracking .jss356.MuiSwitch-input').checked).notEql()
        .click('#geolocationTracking .jss356.MuiSwitch-input')
        .expect(Selector('#geolocationTracking label').withText('POSITION UPDATE LIMIT (MINUTES)').innerText).eql("POSITION UPDATE LIMIT (MINUTES)")
        .expect(Selector('#geolocationTracking .MuiInputBase-input.MuiInput-input').nth(1).visible).ok()
        .typeText(Selector('#geolocationTracking .MuiInputBase-input.MuiInput-input').nth(1), '10')
        .pressKey('enter')
        .expect(Selector('#geolocationTracking label').withText('AUTO REFRESH (MINUTES)').innerText).eql("AUTO REFRESH (MINUTES)")
        .expect(Selector('#geolocationTracking [class^="MuiSelect-root MuiSelect-select MuiSelect-selectMe"]').nth(1).visible).ok()
        .click(Selector('#geolocationTracking div').withText('​').nth(9))
        .expect(Selector('#menu- li').withText('Disabled').innerText).contains("Disabled")
        .click(Selector('#menu- li').withText('5'))
        .expect(Selector('#geolocationFilterSelector label').withText('Route').innerText).contains("Route")
        .expect(Selector('#geolocationFilterSelector .jss356').nth(1).checked).notOk()
        .click(Selector('#geolocationFilterSelector .jss356').nth(1))
        .expect(Selector('#geolocationTracking label').withText('VISITOR').innerText).eql("VISITOR")
        .expect(Selector('#downshift-input-2').visible).ok()
        .typeText('#downshift-input-2', 'muf_tester')
        .click('#downshift-1-item-0')
        .expect(Selector('#geolocationTracking label').withText('DATE').innerText).eql("DATE")
        .expect(Selector('#geolocationTracking [class^="MuiInputBase-input MuiInput-input MuiInputBase-inp"]').visible).ok()
        .expect(Selector('#geolocationTracking .MuiButtonBase-root.MuiIconButton-root').nth(6).visible).ok()
        .click(Selector('#geolocationTracking .MuiButtonBase-root.MuiIconButton-root').nth(6))
        .expect(Selector('button').withText('CLEAR').visible).ok()
        .expect(Selector('button').withText('CANCEL').visible).ok()
        .expect(Selector('button').withText('OK').visible).ok()
        .click(Selector('button').withText('13'))
        .click(Selector('button').withText('OK'))
        .expect(Selector('#geolocationTracking label').withText('PLANNED VS. REAL LOCATION DISTANCE (METERS)').innerText).eql("PLANNED VS. REAL LOCATION DISTANCE (METERS)")
        .expect(Selector('#geolocationTracking .MuiInputBase-input.MuiInput-input').nth(2).value).contains("100")
        .click(Selector('#geolocationTracking .MuiInputBase-input.MuiInput-input').nth(2))
        .pressKey('backspace')
        .pressKey('backspace')
        .pressKey('backspace')
        .typeText(Selector('#geolocationTracking .MuiInputBase-input.MuiInput-input').nth(2), '50')
        .expect(Selector('#geolocationTracking label').withText('AUTO REFRESH (MINUTES)').innerText).eql("AUTO REFRESH (MINUTES)")
        .expect(Selector('#geolocationTracking div').withText('​').nth(9).visible).ok()
        .click(Selector('#geolocationTracking div').withText('​').nth(9))
        .expect(Selector('#menu- li').withText('Disabled').innerText).contains("Disabled")
        .click(Selector('#menu- li').withText('Disabled'))
        .click(Selector('#geolocationTracking .MuiButtonBase-root.MuiIconButton-root').nth(6))
        .click(Selector('span').withText('5'))
        .click(Selector('button').withText('OK'))
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(2))
        .expect(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3).visible).ok()
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3))
        .expect(Selector('#shiftDetailDialog h2').withText('Shift detail for muf_tester(2024-02-05)').textContent).contains("Shift detail for muf_tester(2024-02-05)")
        .expect(Selector('th').withText('SHIFT STARTED').innerText).eql("SHIFT STARTED")
        .expect(Selector('th').withText('SHIFT ENDED').innerText).eql("SHIFT ENDED")
        .expect(Selector('th').withText('TRAVELLED DISTANCE').innerText).eql("TRAVELLED DISTANCE")
        .expect(Selector('button').withText('HIDE').visible).ok()
        .click(Selector('button').withText('HIDE'));
});