import { Selector } from 'testcafe';

fixture `New Fixture`
    .page `http://mus.ph00a1.cz.infra/ui/`;
    
test(`New Test`, async t => {
    await t
        .typeText('#IDToken1', 'much_tester')    
        .typeText('#IDToken2', 'much_tester')
        .click('#kc-login')
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#VISIT_IMPORT_EXPORT li').withText('Visit import / export'))
        .click('#generateFileButton')
        .click(Selector('#unassigned-export button').withText('REFRESH'))
        .click(Selector('#jobQueueTable button').withText('REFRESH'))
        .expect(Selector('#jobQueueTable td').withText('Export unassigned').withText('Export unassigned').visible).ok()
        .expect(Selector('header').nth(1).find('h6').withText('Visit import / export').innerText).eql('Visit import / export')

    await t
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#GLOBAL_VISIT_OVERVIEW li').withText('Visit overview'))
        .click('#mui-component-select-visitCaseTypes')
        .click(Selector('#menu-visitCaseTypes li').withText('Late Field Collection'))
        .click('#menu-visitCaseTypes div')
        .click('#mui-component-select-visitCaseStates')
        .click(Selector('#menu-visitCaseStates li').withText('Unassigned'))
        .click('#menu-visitCaseStates div')
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3))
        .click(Selector('#globalVisitTableContainer [class^="MuiButtonBase-root MuiIconButton-root MuiIconButto"]').nth(3))
        .click(Selector('.MuiButtonBase-root.MuiIconButton-root').nth(36))

    await t
        .click(Selector('#menuButton'))
        .click(Selector('#ASSIGNMENT_MANAGEMENT li').withText('Assignment management'))
        .click('#mui-component-select-visitCaseTypes')
        .click(Selector('#menu-visitCaseTypes li').withText('Early Field Collection'))
        .click(Selector('#menu-visitCaseTypes li').withText('Field Collection Agency'))
        .click('#menu-visitCaseTypes div')
        .click('#mui-component-select-visitCaseStates')
        .click(Selector('#menu-visitCaseStates li').withText('Unassigned'))
        .click('#menu-visitCaseStates div')
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3))
        .click(Selector('#assignmentManagementTableContainer [data-indeterminate="false"]').nth(1))
        .click(Selector('#assignmentManagementTableContainer div').nth(12).find('table tbody tr').nth(1).find('td span span input'))
        .click(Selector('.jss707').nth(4))
        .click('#selectedButton')
        .click(Selector('#assignmentManagementTableContainer [data-indeterminate="false"]').nth(7))
        .click('#selectedButton')
        .click('#cancelButton')
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#AUTO_PREASSIGNMENT li').withText('Auto pre-assignment'))
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#GLOBAL_USER_MANAGEMENT li').withText('User management'))
        .typeText(Selector('#globalUserManagementDashboard .MuiInputBase-input.MuiInput-input').nth(2), 'muf_tester')
        .click(Selector('#searchResultsButton'))
        .click(Selector('button').withText('ENROLL'))
        .click('#addEnrollmentButton')
        .click(Selector('#Region div').withText('​').nth(2))
        .click(Selector('#menu- li').withText('ZIP: 2441'))
        .click(Selector('#Role\\ type div').withText('​').nth(2))
        .click(Selector('#menu- li').withText('Visitor'))
        .click(Selector('#Visit\\ case\\ type div').withText('​').nth(2))
        .click(Selector('#menu- li').withText('FCA'))
        .click('#saveEnrollmentButton')
        .click(Selector('button').withText('CLOSE'))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#TEMPLATE_MANAGEMENT li').withText('Template management'))
        .click(Selector('#Visit\\ case\\ type div').withText('​').nth(2))
        .click(Selector('#menu- li').withText('Early Field Collection'))
        .click(Selector('#Template\\ type div').withText('​').nth(2))
        .click(Selector('#menu- li').withText('Visit template'))
        .click(Selector('#templateManagementTable button').withText('EDIT'))
        .expect(Selector('header').nth(2).find('[class^="MuiButtonBase-root MuiIconButton-root MuiIconButto"]').nth(4).visible).ok()
    await t
        .click(Selector('#closeTemplateButton'))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#VISITOR_MONITORING li').withText('Visitor monitoring'))
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(2))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#CALL_RECORDING li').withText('Call recordings'))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#SYSTEM_ADMINISTRATION li').withText('System administration'))
        .click(Selector('#systemAdministrationDashboard .MuiSvgIcon-root').nth(2))
        .expect(Selector('#systemAdministrationDashboard h6').withText('Serviceable areas').innerText).eql('Serviceable areas')
    await t
        .click(Selector('#systemAdministrationDashboard .MuiSvgIcon-root').nth(16))
        .click(Selector('#systemAdministrationDashboard [class^="MuiButtonBase-root MuiIconButton-root MuiExpansion"]').nth(1))
        .click(Selector('#systemAdministrationDashboard [class^="MuiButtonBase-root MuiIconButton-root MuiExpansion"]').nth(2))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#AGENCY_PORTAL span').withText('Agency portal'))
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(2))
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root MuiIconButto"]'))
        .click(Selector('header').nth(1).find('button').withText('LOG OUT'))

    await t
        .click(Selector('header').nth(1).find('[class^="MuiButtonBase-root MuiIconButton-root jss152 MuiIc"]'))
        .click(Selector('#ASSIGNMENT_MANAGEMENT li').withText('Assignment management'))
        .click('#mui-component-select-visitCaseTypes')
        .click(Selector('#menu-visitCaseTypes li').withText('Field Collection Agency'))
        .click(Selector('#menu-visitCaseTypes li').withText('Field Quality Assurance'))
        .click('#menu-visitCaseTypes div')
        .click('#mui-component-select-visitCaseStates')
        .click(Selector('#menu-visitCaseStates li').withText('Unassigned'))
        .click('#menu-visitCaseStates div')
        .click(Selector('header').nth(2).find('.MuiButtonBase-root.MuiIconButton-root').nth(3))
    
});

