name: MUCH WebUI Tests POC
on:
  push:
    branches: [master]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout
      - name: Install TestCafe
        run: npm install -g testcafe
      - name: Run tests
        uses: testcafe chrome tests
