name: MUCH WebUI Tests POC
on:
  push:
    branches: [master]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    runs-on: node-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: latest
      - name: Run tests
        uses: actions/checkout@v2
        with:
          args: chrome tests

